name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  build-linux:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies for systray
        run: |
          sudo apt-get update
          sudo apt-get install -y libayatana-appindicator3-dev pkg-config
      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 go build -o colima-gui-linux
      - uses: actions/upload-artifact@v4
        with:
          name: colima-gui-linux
          path: colima-gui-linux

  build-windows:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') || github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build Windows binary
        run: go build -o colima-gui.exe
      - uses: actions/upload-artifact@v4
        with:
          name: colima-gui.exe
          path: colima-gui.exe

  build-macos:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') || github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build macOS binary
        run: go build -o colima-gui-darwin
      - uses: actions/upload-artifact@v4
        with:
          name: colima-gui-darwin
          path: colima-gui-darwin

  release:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') || github.event.pull_request.merged == true
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./artifacts/**/*
